# .github/workflows/huggingface-deploy.yml
name: Huggingface Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Authenticate with Huggingface
      run: |
        huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

    - name: Deploy to Huggingface
      run: |
        huggingface-cli repo create my-streamlit-app --type=space --private
        huggingface-cli repo upload --repo-id <username>/my-streamlit-app app.py requirements.txt
        huggingface-cli space hardware --repo-id <username>/my-streamlit-app --hardware cpu-basic