name: Huggingface Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with Huggingface
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      run: huggingface-cli login --token $HF_TOKEN

    - name: Push code to Huggingface Space
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      run: |
        # Replace with your username and space name
        SPACE_REPO="https://huggingface.co/spaces/YOUR_USERNAME/my-streamlit-app"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote add space "https://user:$HF_TOKEN@huggingface.co/spaces/YOUR_USERNAME/my-streamlit-app"
        git push space main --force